export const productHorzotaldtaGet = [
  {
    id: 1,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 2,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 3,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 4,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 5,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 6,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 7,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
  {
    id: 8,
    image: Images['laptop'],
    title: 'Laptop macbook air',
    price: '$432',
    eye: Images['eye_open'],
    heart: Images['heart'],
  },
];
